apiVersion: v1
kind: Service
metadata:
  labels:
    app: moshi-moshi
  name: moshi-moshi
  namespace: moshi-moshi
spec:
  ports:
  - name: http
    appProtocol: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: moshi-moshi
  sessionAffinity: None
  type: ClusterIP
