name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pull-requests: read
  checks: read
  actions: read
  statuses: read

jobs:
  ghcr_publish:
    name: "Publish Docker Image to GHCR"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            persist-credentials: false

        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3 # zizmor complains here, but this is an official partner.
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build Docker image
          run: |
            docker image build -t ghcr.io/${{ github.repository }}:latest .

        - name: Push Docker image
          run: |
            docker image push ghcr.io/${{ github.repository }}:latest
